root: true
env:
  node: true
  browser: true
extends:
  - 'plugin:prettier/recommended'
  - "plugin:react/recommended"
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
plugins:
  - "@typescript-eslint"
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2020
  sourceType: 'module'
  ecmaFeatures:
    jsx: false
settings:
  react:
    pragma: React
    version: detect
rules:
  '@typescript-eslint/no-var-requires': 'off'